name: Docker

on:
  push:
      branches:
      - master

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          -name: Checkout repository
          uses: actions/checkout@v2

            -name: Build the project
            run: |
              echo "Building rhe project."
              ./build.sh


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -name: Checkout repository
        uses: actions/checkout@v2

      -name: Run test
        run: |
            echo "Running tests."
            ./test.sh

    deploy:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/master'
      steps:
        -name: Checkout repository
          uses: actions/checkout@v2

        -name: Deploy the project
          run: |
              echo "Deploying the project."
              ./deploy.sh
